### ISSUE TITLE
Facebook sign in not working in production

### ISSUE THREAD

**Issue by cubadomingo** [cubadomingo/words_and_moves#16]
Hey so I tried testing the facebook sign in and it's not working. Here's what I got:
<img width="1193" alt="screen shot 2016-07-27 at 12 03 18 am" src="https://cloud.githubusercontent.com/assets/15992549/17163458/94550890-538d-11e6-8782-fd0caed397d0.png">

My guess is that maybe the domain you put was www.wordsandmoves.com, which is active but is currently just showing a "welcome to nginx" page.

So all domains and subdomains are:

- www.wordsandmoves.com

- wordsandmoves.com

**Comment by tmobaird** [comment]
Ah I know what the problem is. For the current time since we've been developing a lot lately I set the application address to localhost. I need to set this back though in the facebook dev portal to our domain. That should make this work. I'll knock this out tomorrow morning so we can re-deploy to prod

**Comment by cubadomingo** [comment]
Sounds good bro! Thanks!

**Comment by tmobaird** [comment]
Should be working now. Test it real quick if you don't mind, then close this out 👍

**Comment by cubadomingo** [comment]
Great job 👊
