### ISSUE TITLE
Navbar after user logs in and CSS for feed page

### ISSUE THREAD

**Issue by cubadomingo** [cubadomingo/words_and_moves#45]

**Comment by cubadomingo** [comment]
So I have a new found hatred for CSS. After trying to get the navbar to work with bootstrap styling for a couple of hours I realized I was getting no where. I ditched the majority of the bootstrap styling for the navbar and built it custom. Here are some examples so far. Feed stays the same but the region name changes, as well as when a user is signed in and not. What do you think?

<img width="1198" alt="screen shot 2016-07-31 at 10 21 42 pm" src="https://cloud.githubusercontent.com/assets/15992549/17282012/2f8284ac-576f-11e6-93b9-e8803f3c7486.png">

<img width="1201" alt="screen shot 2016-07-31 at 10 31 19 pm" src="https://cloud.githubusercontent.com/assets/15992549/17282014/33522dbc-576f-11e6-9b15-e8ef64482032.png">

<img width="1200" alt="screen shot 2016-07-31 at 10 32 11 pm" src="https://cloud.githubusercontent.com/assets/15992549/17282017/378c1c80-576f-11e6-808d-7bb5940d98b0.png">

**Comment by tmobaird** [comment]
I actually really like all of those. I can't really decide on one, so I'll leave that final decision up to you, but the first and last ones are my favorite. Since they're pretty similar in structure, feel free to add the CSS for the both of them to our CSS files so we can interchange them easily if we want :ok_hand:
